#spring.datasource.url: jdbc:postgresql://database-1.clmwuysmy0m5.ap-northeast-2.rds.amazonaws.com:5432/postgres
#spring.datasource.username: postgres
#spring.datasource.password: qkrcksrb123
#?? ??? ?? ?? password??

spring:
  datasource: #url, username, password 3??? ???
    url: jdbc:postgresql://database-1.clmwuysmy0m5.ap-northeast-2.rds.amazonaws.com:5432/postgres
    # jdbc: 데이터베이스 종류 : // 주소:포트/데이터베이스 이름
    username: postgres
    password: qkrcksrb1234
    hikari: #hikari ???? ????? ??
      maximum-pool-size: 1
      minimum-idle: 1
  jpa:
    generate-ddl: true  # create, drop ?? ??
